### ISSUE TITLE
MongoDB auto-generated _id

### ISSUE THREAD

**Issue by SkiaBr23** [RADAR-CNS/RADAR-MongoDbConnector#27]
Hello,

Is there a way to make MongoDB overwrite the key sent in the avro from Kafka to its own auto-generated _id as an ObjectID, like in the manual inserts? My application should only send the information to kafka and let the database worry with the _id.  

Thanks in advance.

**Comment by SkiaBr23** [comment]
I actually solved that problem by creating my on RecordConverter, thanks for documenting some of that on the project readme.

**Comment by blootsvoets** [comment]
Great that you found a solution! If you have a general solution, feel free to open a pull request!
