### ISSUE TITLE
Exception from MongoDB storage gets ignored

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-MongoDbConnector#3]
In the `MongoDbHelper.storeIgnoreError(String, Document)` function, any error from MongoDB gets logged but then ignored. This means that data that produces the error will never reach MongoDB. Should it re-throw the exception instead?

**Comment by fnobilia** [comment]
Any exception that might cause data loss should be re-throw. In this way the commit phase cannot be trigger and data causing the exception can be re-read.
