### ISSUE TITLE
Sink only taking out 1 item from my topic - 1 document in my collection

### ISSUE THREAD

**Issue by psmod2** [RADAR-CNS/RADAR-MongoDbConnector#33]
Hi,

In my topic I have 100 topics. I setup the connector with the following configuration:

```
        CONNECT_BOOTSTRAP_SERVERS: kafka:9092
        CONNECT_GROUP_ID: "my-connector-mongodb-sink"
        CONNECT_CONFIG_STORAGE_TOPIC: "mongodb-sink-configs"
        CONNECT_OFFSET_STORAGE_TOPIC: "mongodb-sink-offsets"
        CONNECT_STATUS_STORAGE_TOPIC: "mongodb-sink-status"
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
        CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
        CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
        CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
        CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
        CONNECT_REST_HOST_NAME: 0.0.0.0
        CONNECT_REST_ADVERTISED_HOST_NAME: 0.0.0.0
        CONNECT_REST_PORT: 9000
        CONNECT_PLUGIN_PATH: "/usr/share/java/kafka-connect-mongodb-sink-0.2.1.jar"
```

And the remaining config:

```
{
  "connector.class": "org.radarcns.connect.mongodb.MongoDbSinkConnector",
  "mongo.database": "sinktest",
  "mongo.host": "mongo",
  "topics": "bxB",
  "tasks.max": "1",
  "name": "MongoDbSinkConnector"
}
```

However when I look at my MongoDB collection I only see the very last topic entry.

Any ideas why?

Infact - i just realised the offset is set at 100 - whats controlling that. The OFFSET_STORAGE_TOPIC: "mongodb-sink-offsets" is unique and not being used by anything else.

![screen shot 2018-05-01 at 17 01 33](https://user-images.githubusercontent.com/15928263/39465994-6f37ab74-4d61-11e8-9584-01053720cd4c.png)

**Comment by yatharthranjan** [comment]
Hi, can you please also post the logs of the Mongodb connector when it is running?
Thanks

**Comment by yatharthranjan** [comment]
@psmod2 is the key for each record the same in the above topic bxB ?

**Comment by psmod2** [comment]
@yatharthranjan - yes the key for each topic entry is the same. Could that be the cause? Well there really isn't any key - its just the same String. SO does this mean I'll need to set some randomly generated key value myself?

**Comment by yatharthranjan** [comment]
Hi @psmod2 , yes that would be the reason. If you want all the records you can try using a different unique key for each record. Or you can just not include a key in your record. Please refer to #34 for more info. Thanks

**Comment by yatharthranjan** [comment]
Closing this for now. Reopen if not fixed
