### ISSUE TITLE
Have a configurable option to optimize the mongodb writer

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-MongoDbConnector#34]
Right now the mongoDb writer just writes the latest values for each id in each topic. See here - https://github.com/RADAR-base/MongoDb-Sink-Connector/blob/46ea3af8652e8ca6cd6c9de9880495c9204aac1d/src/main/java/org/radarcns/connect/mongodb/MongoDbWriter.java#L146 
This is important for performance when dealing with large amounts of data from the streams apps.
But this is not ideal for someone who wants to use the mongoDb connector standalone and wants to write all the data from topics to the mongoDb. 
Create a config option to handle this case which can be specified in the sink-mongodb.properties file
This may also help solve #33

**Comment by blootsvoets** [comment]
The behaviour of MongoDB is that if two records with the same ID are written, the first one is overwritten. This is consistent with what the connector does, only the connector does it before writing to MongoDB. Users can specify a custom converter to generate those IDs, so if each converted record gets a unique ID, or does not get an ID at all, no substitution takes place, again, consistent with how MongoDB behaves.
