### ISSUE TITLE
Support mongo+srv URLs

### ISSUE THREAD

**Issue by alexjg** [RADAR-CNS/RADAR-MongoDbConnector#44]
Hey folks, as far as I can tell this connector doesn't support using `mongo+srv` style hosts. This is a problem if using services - such as MongoDBs hosted Atlas service - which publish their addresses as `SRV` records. 

One simple solution would probably be to allow specifying a connection string and checking if it's present in the config then using the `MongoClientURI` based constructor for `MongoClient`?

**Comment by blootsvoets** [comment]
Thanks for the suggestion. We could probably change the settings to accept a URI instead of the current host/port. Conveniently, this URI also encodes the username/password if any.

**Comment by blootsvoets** [comment]
Should be fixed in the `dev` branch.
