### ISSUE TITLE
Storing offsets inside a MongoDb collection

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-MongoDbConnector#6]
Now the connector does not distinguish the first run from reboots: it alway writes all extracted SinkRecords without check whether they have been already stored.

We can solve this issue storing the last written offsets for each topic inside a MongoDb collection. In this way the same message will be no longer written more than once.

There are tow possible solutions:
1.  we can modify `public synchronized void flush(Map<TopicPartition, OffsetAndMetadata> offsets)` in `org.radarcns.mongodb.MongoDbWriter`. At the end of the write phase, the `flush` function will store the last flushed Kafka offsets of each topic inside a MongoDb collection.
2. we can modify `private void store(SinkRecord record, int tries)` in `org.radarcns.mongodb.MongoDbWriter` storing first the message and then the related offset. Each SinkRecord will require two MongoDb inserts one for the data and one for the offset

Upon start, `MongoDbSinkConnector` will fetch the last written offsets from MongoDb and it will forward the metadata to the `org.radarcns.mongodb.MongoDbSinkTask`. Then `public void put(Collection<SinkRecord> sinkRecords)` of `MongoDbSinkTask ` will escape all SinkRecords having offsets smaller than the last flushed offset read form the MongoDb collection for the given topic.

[1] adds a very small overhead for the `flush` function, while the performance for the `put` will be considerably improved in case of rebooting. This enhancement will provide *exactly once* delivery for offsets committed by Kafka.

[2] provide **exactly once** delivery at the price of huge overhead: the MongoDb writes will be doubled. In case of rebooting, the `put` function will achieve better performance than [1], but it will suffer an overhead during normal executions.

**Comment by nivemaham** [comment]
Can i close this issue @blootsvoets , @fnobilia ?

**Comment by blootsvoets** [comment]
Yes - perhaps its time for a PR then as well.
